version: 2
updates:
  - package-ecosystem: npm
    directory: /web-ui-editor
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
